require: rubocop-rspec

inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.2
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/*'
    - 'config/deploy.rb'

Lint/UnusedBlockArgument:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Max: 31
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'lib/tasks/dev.rake'
    - 'spec/**/*'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/SymbolProc:
  Exclude:
    - 'spec/factories/**/*'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Layout/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Layout/IndentHash:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Layout/LeadingCommentSpace:
  Exclude:
    - 'spec/**/*'

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Layout/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/OutputSafety:
  Exclude:
    - 'app/presenters/rtl_index_presenter.rb'
    - 'app/presenters/rtl_show_presenter.rb'

Rails/DynamicFindBy:
  Exclude:
    - 'app/controllers/exhibits_controller.rb'
    - 'app/models/exhibit_proxy.rb'
    - 'app/decorators/applies_title_from_slug.rb'
    - 'app/values/manifest_metadata.rb'

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/DescribeClass:
  Exclude:
    - 'spec/abilities/**/*'
    - 'spec/features/**/*'
    - 'spec/views/**/*'
    - 'spec/routing/**/*'
    - 'spec/inputs/**/*'

Naming/FileName:
  Exclude:
    - 'Capfile'
    - 'Gemfile'
RSpec/AnyInstance:
  Exclude:
    - 'spec/support/stub_iiif_response.rb'
