---
version: 2
jobs:
  build:
    working_directory: ~/pomegranate
    docker:
      # The primary container is an instance of the first list image listed. Your build commands run in this container.
      - image: circleci/ruby:2.6-node-browsers
        environment:
          RAILS_ENV: test
          NODE_ENV: test
          POMEGRANATE_DB_HOST: localhost
          POMEGRANATE_DB_USERNAME: pomegranate
          POMEGRANATE_DB_PASSWORD: ""
    steps:
      - checkout
      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: pomegranate-{{ checksum "Gemfile.lock" }}
      - type: cache-restore
        name: Restore Yarn cache
        key: pomegranate-yarn-{{ checksum "yarn.lock" }}-1
      - run:
          name: Install node@lts/erbium (need right version for `yarn`)
          command: |
            set +e
            touch $BASH_ENV
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            echo 'nvm install lts/erbium' >> $BASH_ENV
            echo 'nvm alias default lts/erbium' >> $BASH_ENV
      - run:
          name: Check current version of node
          command: node -v
      - run:
          name: Install NPM dependencies via Yarn
          command: yarn install --frozen-lockfile
      # Install Bundler
      - run: gem install bundler -v '~> 2.0'
      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      # Cache Dependencies
      - type: cache-save
        name: Save Yarn package cache
        key: pomegranate-yarn-{{ checksum "yarn.lock" }}-1
        paths:
          - ~/.cache/yarn
      - type: cache-save
        name: Store bundle cache
        key: pomegranate-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      - persist_to_workspace:
          root: '~/pomegranate'
          paths: '*'
  rubocop:
    working_directory: ~/pomegranate
    docker:
      - image: circleci/ruby:2.6-node-browsers
        environment:
          RAILS_ENV: test
          POMEGRANATE_DB_HOST: localhost
          POMEGRANATE_DB_USERNAME: pomegranate
          POMEGRANATE_DB_PASSWORD: ""
    steps:
      - attach_workspace:
          at: '~/pomegranate'
      # Install Bundler
      - run: gem install bundler -v '~> 2.0'
      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      - run: bundle exec rake rubocop
  test:
    working_directory: ~/pomegranate
    docker:
      - image: circleci/ruby:2.6-node-browsers
        environment:
          RAILS_ENV: test
          POMEGRANATE_DB_HOST: localhost
          POMEGRANATE_DB_USERNAME: pomegranate
          POMEGRANATE_DB_PASSWORD: ""
          SOLR_URL: "http://localhost:8984/solr/blacklight-core-test"
      - image: postgres:10.3
        environment:
          POSTGRES_DB: dpul_test
          POSTGRES_USER: pomegranate
          POSTGRES_PASSWORD: ""
      - image: solr:7.7-alpine
        command: bin/solr -cloud -noprompt -f -p 8984
    steps:
      - attach_workspace:
          at: '~/pomegranate'
      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Install node@lts/erbium (need right version for `yarn`)
          command: |
            set +e
            touch $BASH_ENV
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            echo 'nvm install lts/erbium' >> $BASH_ENV
            echo 'nvm alias default lts/erbium' >> $BASH_ENV
      - run:
          name: Check current version of node
          command: node -v
      # Install Bundler
      - run: gem install bundler -v '~> 2.0'
      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      - run:
          name: Load config into solr
          command: |
            cd ~/pomegranate/solr/config
            zip -1 -r solr_config.zip ./*
            curl -H "Content-type:application/octet-stream" --data-binary @solr_config.zip "http://localhost:8984/solr/admin/configs?action=UPLOAD&name=dpul"
            curl -H 'Content-type: application/json' http://localhost:8984/api/collections/ -d '{create: {name: blacklight-core-test, config: dpul, numShards: 1}}'
      - run: bundle exec rake db:create
      - run: bundle exec rake db:migrate
      - run: COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN bundle exec rspec spec
      
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - rubocop:
          requires:
            - build
      - test:
          requires:
            - build
