defaults: &defaults
  all_collection_manifest_url: "https://figgy.princeton.edu/iiif/collections"
  external_universal_viewer_url: "https://figgy.princeton.edu/uv/uv"
  external_universal_viewer_config_url: "https://figgy.princeton.edu/viewer/exhibit/config"
  events:
    server: 'amqp://localhost:5672'
    exchange: 'plum_events'

development:
  <<: *defaults

test:
  <<: *defaults
  all_collection_manifest_url: "https://hydra-dev.princeton.edu/iiif/collections"

production:
  <<: *defaults
  all_collection_manifest_url: <%= ENV["POMEGRANATE_COLLECTIONS_URL"] %>
  events:
    server: <%= ENV["POMEGRANATE_RABBITMQ_URL"] %>
    exchange: <%= ENV["POMEGRANATE_RABBITMQ_EXCHANGE"] %>

staging:
  <<: *defaults
  all_collection_manifest_url: <%= ENV["POMEGRANATE_COLLECTIONS_URL"] %>
  events:
    server: <%= ENV["POMEGRANATE_RABBITMQ_URL"] %>
    exchange: <%= ENV["POMEGRANATE_RABBITMQ_EXCHANGE"] %>
