defaults: &defaults
  universal_viewer_url: "http://uv-dev.princeton.edu/lib/embed.js"
  all_collection_manifest_url: "https://hydra-dev.princeton.edu/iiif/collections"
  events:
    server: 'amqp://localhost:5672'
    exchange: 'plum_events'

development:
  <<: *defaults
  all_collection_manifest_url: "http://localhost:3000/iiif/collections"

test:
  <<: *defaults

production:
  <<: *defaults

staging:
  <<: *defaults
