defaults: &defaults
  all_collection_manifest_url: "https://figgy.princeton.edu/iiif/collections"
  external_universal_viewer_url: "https://figgy.princeton.edu/viewer"
  external_universal_viewer_config_url: "https://figgy.princeton.edu/viewer/exhibit/config"
  manifest_authorization_token: <%= ENV["POMEGRANATE_MANIFEST_AUTH_TOKEN"] || "" %>
  events:
    server: 'amqp://localhost:5672'
    exchange: 'plum_events'
  event_queue:
    durable: true

development:
  <<: *defaults

test:
  <<: *defaults
  all_collection_manifest_url: "https://hydra-dev.princeton.edu/iiif/collections"

production:
  <<: *defaults
  all_collection_manifest_url: <%= ENV["POMEGRANATE_COLLECTIONS_URL"] %>
  events:
    server: <%= ENV["POMEGRANATE_RABBITMQ_URL"] %>
    exchange: <%= ENV["POMEGRANATE_RABBITMQ_EXCHANGE"] %>

staging:
  <<: *defaults
  all_collection_manifest_url: <%= ENV["POMEGRANATE_COLLECTIONS_URL"] %>
  external_universal_viewer_url: <%= ENV["POMEGRANATE_COLLECTIONS_URL"].to_s.gsub(/edu\/.*/, "edu/viewer") %>
  external_universal_viewer_config_url: <%= ENV["POMEGRANATE_COLLECTIONS_URL"].to_s.gsub(/edu\/.*/, "edu/viewer/exhibit/config") %>
  events:
    server: <%= ENV["POMEGRANATE_RABBITMQ_URL"] %>
    exchange: <%= ENV["POMEGRANATE_RABBITMQ_EXCHANGE"] %>
  event_queue:
    durable: false
