default: &default
  adapter: postgresql
  encoding: unicode

development: &development
  <<: *default
  host: <%= ENV["lando_dpul_development_db_conn_host"] || ENV["POMEGRANATE_DB_HOST"] || "localhost" %>
  port: <%= ENV["lando_dpul_development_db_conn_port"] || "5432" %>
  username: <%= ENV["lando_dpul_development_db_creds_user"] || ENV["POMEGRANATE_DB_USERNAME"] %>
  password: <%= ENV["lando_dpul_development_db_creds_password"] || ENV["POMEGRANATE_DB_PASSWORD"] %>
  database: dpul_development

test:
  <<: *default
  host: <%= ENV["lando_dpul_test_db_conn_host"] || ENV["POMEGRANATE_DB_HOST"] || "localhost" %>
  port: <%= ENV["lando_dpul_test_db_conn_port"] || "5432" %>
  username: <%= ENV["lando_dpul_test_db_creds_user"] || ENV["POMEGRANATE_DB_USERNAME"] %>
  password: <%= ENV["lando_dpul_test_db_creds_password"] || ENV["POMEGRANATE_DB_PASSWORD"] %>
  database: dpul_test

production: &deploy
  <<: *default
  adapter: postgresql
  host: <%= ENV["POMEGRANATE_DB_HOST"] %>
  database: <%= ENV["POMEGRANATE_DB"] %>
  username: <%= ENV["POMEGRANATE_DB_USERNAME"] %>
  password: <%= ENV["POMEGRANATE_DB_PASSWORD"] %>
  pool: 40

staging:
  <<: *deploy
