# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development: &default
  adapter: postgresql
  database: dpul_development
  encoding: utf8
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 30)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000

test:
  <<: *default
  database: dpul_test


production: &production
  <<: *default
  adapter: postgresql
  database: <%= ENV["POMEGRANATE_DB"] %>
  host: <%= ENV["POMEGRANATE_DB_HOST"] %>
  username: <%= ENV["POMEGRANATE_DB_USERNAME"] %>
  password: <%= ENV["POMEGRANATE_DB_PASSWORD"] %>
  pool: 40

staging:
  <<: *production
