development:
  host: <%= ENV["lando_redis_conn_host"] || "localhost" %>
  port: <%= ENV["lando_redis_conn_port"] || 6379 %>
test:
  host: <%= ENV["lando_redis_conn_host"] || "localhost" %>
  port: <%= ENV["lando_redis_conn_port"] || 6379 %>
  db: 2
production: &production
  host: <%= ENV['POMEGRANATE_REDIS_URL'] || 'localhost' %>
  port: <%= ENV['POMEGRANATE_REDIS_PORT'] || '6379' %>
  db: <%= ENV['POMEGRANATE_REDIS_DB'] || 0 %>
staging:
  <<: *production
